name: SOLVATECH
favicon: null
layout_spectrum: 0
typography_spectrum: 0.20824331534095109
title: SOLVATECH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18364e'
    - '#3d698e'
    - '#000000'
    - '#8abcf7'
    - '#8588a9'
  brandStrength: 0.7048549519386142
  lightness: 0.4891428519040346
  saturation: 0.31135002127848566
  rhythmicContrast: 0.6007595025002956
purpose: []
